### PR TITLE
Swift 4.2 and Xcode 10 Support

### PR DESCRIPTION
**Pull request by kurabi**
- Swift 4.2 Support
- Xcode 10 Support

This branch will be kept up to date with master. This will ship when Xcode 10 GM is released. 

To use this as a `beta` via Cocoapods:
```ruby 
pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'swift_4.2'
```

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
Xcode 10 GM has shipped. Mind merging? :)

**Comment by kurabi** [comment]
Will do tomorrow.

**Comment by aaronbrethorst** [comment]
splendid, thank you!

**Comment by JonyFang** [comment]
Hi, bro~ Why isn't there a `swift_4.2` branch now?

**Comment by kurabi** [comment]
It’s on Master now.

**Comment by JonyFang** [comment]
> It’s on Master now.

Thx, got it~😝

**Comment by jordanj-pl** [comment]
I am using Xcode 10.2.1 and the problem still exists.

**Comment by kurabi** [comment]
Update your pod with ‘pod update SwipeCellKit’

**Pull request merged**
