### PR TITLE
Changes to support allowing swipe cells and other gesture recognizers exclusively

### PR DESCRIPTION
**Pull request by plivesey**
Recreating a pull request because the first was closed for lack of activity. We missed that (sorry), but have responded to questions. See previous request: #112

### CODE REVIEW

**Comment by plivesey** [comment]
See #112 for previous conversation. Latest response:

@kurabi sorry the slow response. Just jumping in for @emuye here. We currently have a few custom swipe gestures include one which reveals a menu on the right.

For the open change:
We want to disable these gestures if any cell is currently in the right or left state. To do this, we need to query for this state.

For the .isEnabled change:
This is no longer necessary for our codebase, but without this, you can't make the swipe gesture cancel with the delegate method. Here's what makes most sense to me:

otherGesture requires swipe gesture to fail
swipe gesture asks for actions, but there aren't any actions. So it moves to the cancel state.
This allows otherGesture to fire
Without the .isEnabled change, this is not possible as far as I can tell.

**Comment by kurabi** [comment]
The interactive back gesture in UINavigationController works fine with the SwipeCellKit, I assume you want the exact same behavior. So we should understand why and how that works before making any changes as I feel the solution can be outside this library as demonstrated by the interactive back gesture.

**Comment by plivesey** [comment]
There are two changes in this PR. It seems like you're ok with the first change (adding open), but questioning the second change (cancelling the gesture).

To answer your question:
You say that it 'works fine'. This depends on how you want it to work. If you wanted this behavior:
```
If you edge swipe on a cell that has options, it should not swipe back and instead swipe on the cell.
If you edge swipe on a cell that doesn't have any options, it should swipe back.
```
how would you implement it? I'd think you could do something like:
```
// pseudo code
navigationController.swipeGesture.requireToFail(cell.swipeGesture)
```
but this doesn't work because the swipe gesture on the cell doesn't cancel when there are no buttons.

**Comment by plivesey** [comment]
As far as I can tell, there isn't any way to add behaviors like this? Maybe there's another way though?

**Comment by kurabi** [comment]
Any gesture added, should behave like the interactive back gesture. Meaning, if you add a gesture to open a side menu, it should operate as such:

1. If swiping from edge, regardless if cell has options or not, the menu gesture should take over, like that of the back gesture.
2. If swiping from none-edge, while cell has no options, the menu gesture should take over.

While I think #2 is bad UX, as it confuses users on when a cell can be swiped vs. triggering menu action, I am fine with the library supporting it. However right now, we don't do anything to support the interactive back gesture, it is prioritized over the cell swipe gesture somehow, and I would ideally want to understand how it works, to see if that can be the solution to achieve the above 2 behaviors.

Regrading 
> If you edge swipe on a cell that has options, it should not swipe back and instead swipe on the cell.

Although I also think this is bad UX, the user should simply turn off the interactive back gesture.

**Comment by plivesey** [comment]
In terms of UX, I'm using this as an example of something which is not possible with this library. Sometimes, there are other gestures which you want to do only if a cell swipe fails.

Currently, this isn't possible because the swipe gesture never fails even if it doesn't actually swipe. This just gives users of the library the ability to return nil to indicate failure.

Simply turning off the gesture doesn't necessarily work because sometimes some cells have swipes and other's don't. In our project, we have a few different swipe options which vary on the cell. So some cells can swipe in both directions, some only in one direction (users can differentiate by the UI in the cell).

**Comment by kurabi** [comment]
I am still mulling over the cancellation of the gesture. However, assuming the gesture cancellation is added when no actions exist, why would we want to surface the currently private swipe state?

**Comment by plivesey** [comment]
We have another gesture on our view (a pull down to reveal another controller). We only want this gesture to recognize if no cells are currently open. I don't see any other way of doing this?

**Comment by kurabi** [comment]
A pull down on a table view? 🤔 Like a pull-to-refresh on a `UITableView`? or something else? 

Right now I am convinced to cancel the gesture when no actions exist. However i just need to make sure there is no unintended side effect. Not convinced on why the swipe state would need to be exposed.

**Comment by plivesey** [comment]
It's not a pull to refresh, it's sort of like a swipe to reveal menu controller, but vertical.

**Comment by kurabi** [comment]
@plivesey I added a fix to cancel the pan gesture when no actions exist for that pan orientation per your PR. I opted to patch it my self as I will not be exposing the swipe state as I am not convinced to its utility and some nuances to what gesture reference is being cancelled. I am more than happy to re-consider if I can see an example app demonstrating the need of knowing the swipe state.

**Comment by kurabi** [comment]
@plivesey I had put a solution for this, then pulled it out last second because I saw that the pan gesture cancellation interfered with cell selection. That said I added it back via a SwipeTableOption that you can enable. However, when I was testing with a pan gesture I added, I don't see the gesture isEnabled=false then back to true does anything. It does not seem to yield. So I am wondering how does it work for you? You can look at the `cell_reselection` branch where I have this.

**Comment by plivesey** [comment]
Sorry for the slow response. Was out of town for the weekend.

I checked out the branch, and everything seems to be working correctly. But on the branch you don't have:
`options.cancelGestureRecognizerForEmptySwipeActions = true` in `func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {`

Here's what I found:

After including: `options.cancelGestureRecognizerForEmptySwipeActions = true`
1. Go to the more options
2. Tap disable swipe right
3. Put a break point in .changed for the gesture recognizer
4. Press your finger down on a row and move your finger slightly to the right

Results:
1. The breakpoint never hits
2. If you move your finger a small distance and then raise your finger, it registers as a tap

If I set `cancelGestureRecognizerForEmptySwipeActions` to false, neither of these happen, so it does seem to be working.

Note for #2 here, this seems to match default UITableView behavior which is interesting. As in, if you move your finger slightly to the right or left on a regular table view cell and then raise your finger, it registers as a tap.

**Comment by kurabi** [comment]
I was referring to a local test I was doing where I added a pan gesture recognizer on my `UITableViewController` that prints out a log statement, I could never get that log statement to trigger even though `cancelGestureRecognizerForEmptySwipeActions` was true when panning in the direction where no swipe actions exist.

I do it the swipe pan gesture cancelling, but I only see the cell being selected like you indicated, and never allowing the alternative pan gesture to be invoked.

So my question is, how would an alternative pan gesture work? What else is missing that a developer would do to get their alternative pan gesture to work.

**Comment by plivesey** [comment]
We're currently using https://github.com/John-Lluch/SWRevealViewController for a menu swipe gesture. This adds a pan gesture which you can swipe to reveal a menu on the left. It's probably too much to add to the sample app, but that is an example of a pan gesture which you want to make play nice with the swipe cell gesture.

The enabled/disabled feature though we don't actually need anymore. The more relevant fix is the state fix. Example code which you may want in an app:

```
func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    for cell in tableView.visibleCells {
        if cell.state != .center { return false }
     }
    return true
}
```

**Comment by plivesey** [comment]
But we don't want precedence. We only want it to work if all the swipe cells are centered. So, we have different behavior if you've swiped one of the cells open.

So, if everything is closed, it will act normally.
If you swipe open one cell, then it changes behavior.

**Comment by kurabi** [comment]
I am referring to this statement

> The enabled/disabled feature though we don't actually need anymore.

I assume you are referring to the features in this PR?

Secondly, I cannot get my alternative pan gesture to work. SWReveal must be adding the pan gesture on the UINavigationController that wraps the UIViewController.

**Comment by plivesey** [comment]
The enabled/disabled feature is useful if you want to require it to fail. So you can have:

swipe gesture has priority over other gesture
other gesture requires swipe gesture to fail

Without the `enabled/disabled` feature, if there are no actions and you swipe, the other gesture will not fire (since the swipe gesture is recognizing). Ideally, even if it's prioritized, if it doesn't do anything, other gestures will fire.

**Comment by kurabi** [comment]
Understood. Regarding

> other gesture requires swipe gesture to fail

How can I do this in the example app? I added an alternative pan gesture on my UITableViewController in the sample app. I enabled `cancelGestureRecognizerForEmptySwipeActions`. Yet my alternative gesture is not firing. 

IE, I am trying to replicate that scenario/process that devs will go through, but I am not successful at it. What am I missing?

**Comment by plivesey** [comment]
Yes, I see what you're saying. I couldn't get the pan gesture to work on the tableview either. Not sure how reveal controller is getting around that. But one way to test this is to add a pan gesture to each cell:

```
        let gesture = UIPanGestureRecognizer(target: self, action: #selector(panned(_:)))
        cell.addGestureRecognizer(gesture)
        gesture.delegate = self
        gesture.require(toFail: cell.panGestureRecognizer)
```

Then I just put a print statement in `panned(_:)`. If you turn off swipes and swipe to the left, the gesture doesn't fire. If you swipe to the right (now disabled), the new pan gesture succeeds.

Also, we have made the `panGestureRecognizer` public in our fork, which I just realized.

**Comment by kurabi** [comment]
Adding a `gesture.require(toFail: )` to each cell seems crazy to me. `SWRevealViewController` works because the gesture is higher up the stack in the view. 

That said, I am parking this unless we have more sound reasoning to add this.

**Pull request closed without merging**
