### PR TITLE
fix UI issue.

### PR DESCRIPTION
**Pull request by 623637646**
How to reproduce the UI issue?
1. change the demo code: https://github.com/623637646/SwipeCellKit/commit/847cfb6988accce6ad3bce3837fc1e4354509421
2. go into UICollectionView Example and delete cells one by one from top

### CODE REVIEW

**Comment by kurabi** [comment]
What is the UI issue here? I ran the example code, I did not see an issue.

**Comment by 623637646** [comment]
[Untitled.mov.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/3568965/Untitled.mov.zip)

**Comment by 623637646** [comment]
Screenshot 2019-09-03 at 6 07 42 PM

**Comment by 623637646** [comment]
Hi, @kurabi . This is the screenshot (Refer the first comment to reproduce it ).

**Comment by kurabi** [comment]
> Hi, @kurabi . This is the screenshot (Refer the first comment to reproduce it ).

Thanks, now I see it. It seems like the deleted cell is being reused and is what causes it to be empty, which is odd. `setNeedsLayout` has a small performance impact that I don't want to concede. 

I have committed a fix to `develop` that approaches this problem differently. Let me know if you still see any issues with that fix.

**Comment by 623637646** [comment]
Thanks @kurabi

**Pull request closed without merging**
