### PR TITLE
Add expandImmediately as a new expansion style.

### LINKED ISSUE #202: Cell not stick
Hey, thank you for this awesome library. I'm trying to find a way so when the user swipes the cell the action occurs immediately so without giving the user a chance for the cell to stick and show the available options

### PR DESCRIPTION
**Pull request by 1AmNegan**
Closes #202 
myfeatureswipe

### CODE REVIEW

**Comment by 1AmNegan** [comment]
@kurabi, can you please review this PR?

**Comment by kurabi** [comment]
@1AmNegan Thanks for the PR.

But there is a few things missing:
1. There needs to be a trigger threshold, if you drag to little, it should not trigger the action.
1. When expanding beyond the trigger threshold, an action is suppose to take place immediately, not after the swipe action completes.

**Comment by kurabi** [comment]
Closing this branch as this work is not complete. Will re-open if progress is made.

**Comment by lsmilek1** [comment]
Hello, was there any progress on this topic? Can I contribute anyhow with my limited programming experiance? Thanks!

**Pull request closed without merging**
