### PR TITLE
Add support for UICollectionView with SwipeCollectionViewCell

### PR DESCRIPTION
**Pull request by kreeger**
This pull request supersedes #45.

This is possible in large part thanks to @gcox and @mschonvogel for the initial implementation. This makes a copy of SwipeTableViewCell and bases it on UICollectionViewCell, making plenty of necessary adjustments to calculate translations and frames/centers based on the collection view cell's `contentView` instead of just the cell itself (like the table view cell implementation does). This means we can drag the cell left and right without it overlapping neighbor cells (clipsToBounds is true). Additionally, trigger points for the expansion animations are calculated based on the cell's position within the collection view, and not the whole collection view width like table views are.

As @gcox mentioned in his [original pull request](https://github.com/SwipeCellKit/SwipeCellKit/pull/45), `SwipeTableOptions` has been renamed to `SwipeOptions` since it's not specific to tables in any way. There's also still a fair amount of duplicated code between the two implementations, and it may be worth it to refactor this to reduce that where it makes sense.

Additionally, the example app has been updated with a `UICollectionView` example that uses a `UICollectionViewFlowLayout` set so that cells sit side by side in a 2-wide grid.

screencast

### CODE REVIEW

**Comment by kurabi** [comment]
Thanks for the pull request @kreeger. Going to review this over the next few days as this is a big change.

**Comment by Recouse** [comment]
Will this be merged?

**Comment by kreeger** [comment]
I just discovered and fixed a bug around how the cell animates its dismissal during `.destructive` / `.fill` swipe animations.

**Comment by wcrtr** [comment]
If you create a collection view with cells of type `SwipeCollectionViewCell` mixed with other cells (say you want to have some cells be swipeable and some not, or of a different `UITableViewCell` subclass, then there are issues with the consistency of tapping/selection of events. I think the issue stems from line 510 of `SwipeCollectionViewCell.swift` in the gesture `gestureRecognizerShouldBegin` method. Without digging too much into the logic there I found that if I made all my cells subclasses of  `SwipeCollectionViewCell` then my issue went away. 

This could be a won't fix, or maybe I'm just using this in an unintended way and there isn't actually a bug here. Certainly easy to work around, just wanted to bring it up in case it was unexpected behavior.

**Comment by kurabi** [comment]
@kreeger This is a good start, however there is a lot of duplicate. These are also some other issues need to be addressed. I will merge this into a WIP branch for collection views.

**Comment by kurabi** [comment]
Merged. Next steps are:
- Reduce duplication
- Update Documentation
- Account for Safe Area Inset (ie. iPhone X in landscape)
- Resolve issue where two rows an be swiped simultaneously

**Pull request merged**
