### PR TITLE
Add SwipeDirection option set that allows to define which swipe directions are allowed on a specific cell

### PR DESCRIPTION
**Pull request by julienpouget**
Hi,

I've added a new property (direction) in the Swipeable protocol that allows to define on each cell the allowed directions for the swipe (none, right to left, left to right or both).

I though you might be interested into merging it.
Cheers,
Julien

### CODE REVIEW

**Comment by kurabi** [comment]
If you return zero actions for the orientation then nothing will happen. So can you clarify what this achieves?

**Comment by julienpouget** [comment]
Sorry for the lack of explanation.

I know that if the cell return zero actions for the orientation then nothing will happen.
But in my case, I have actions on each cells for the `.right` orientation and none for the `.left` orientation. In addition to that I have pan gesture recognizer on my navigation controller (the one that contains the table view controller) used to reveal a drawer menu from the left of the screen.

**Comment by julienpouget** [comment]
You mean by implementing one of those two methods : 
`func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldBeRequiredToFailBy otherGestureRecognizer: UIGestureRecognizer) -> Bool`

**Comment by julienpouget** [comment]
About :
> Also, even if the swipecell has only actions on one side, the cell could be panned to the right or left if a user decides to swipe the opposite way to close the cell.

I've handled that case, the swipe is always enabled in both direction if the swiped cell is in an active state.

**Comment by Luccifer** [comment]
Any news about the merge?

**Comment by Luccifer** [comment]
Any news about merge?

**Pull request closed without merging**
