### PR TITLE
fix UIScreenEdgePanGestureRecognizer bug

### PR DESCRIPTION
**Pull request by kaich**

### CODE REVIEW

**Comment by kurabi** [comment]
I am not clear on what the bug is. Is this for the interactive back gesture on a UINavigationController?

**Comment by kaich** [comment]
@kurabi I hav a custom transition for UINavigationController. So I add UIScreenEdgePanGestureRecognizer to the view of UIViewController to swipe back. When I  use SwipeCellKit in my tableView, back gesture don't works fine. (If you use UINavigationController interactivePopGestureRecognizer, it works fine. But I need custom back)

**Comment by kurabi** [comment]
Why does it work fine UINavigationController but not yours? What’s the difference? My point is. Your solution and UINavigationController both use edge pan gesture, what makes it work for back gesture?

**Comment by kaich** [comment]
You can test it with a navigation and set interactivePopGestureRecognizer.isEnable = false. Then you add         
```
       let pan = UIScreenEdgePanGestureRecognizer(target: self, action:#selector(popViewController(_:)))
        pan.edges = .left
        view.addGestureRecognizer(pan)
```
It's a simple test. You will find you can't swipe back with SwipeCellKit.

**Comment by kurabi** [comment]
My point is, how does pan gesture work correctly in UINavigationContoller with SwipeCellKit?

**Comment by kaich** [comment]
`gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool ` to solve two swipe gesture conflict. I add `swipeBeginOffsetX`  default value 10.  you can set custom value.

**Comment by kurabi** [comment]
Why doesn’t this conflict with UINavigationController swipe back gesture?

**Pull request closed without merging**
