### PR TITLE
iOS 13 Dark Mode support

### PR DESCRIPTION
**Pull request by kurabi**
- Changed hard coded colors to use system colors for better dark mode and accessibility support.
- Added SF Display icon support for >= iOS 13 devices in example Mail.app

### CODE REVIEW

**Comment by kreeger** [comment]
I don't know if this is due to Xcode 10 vs Xcode 11 weirdness, but even _with_ the `available(iOS 13.0, *)` statements, this now fails to compile in Xcode 10 because the compiler throws errors about those new colors `systemRed`, `systemGray5` and `systemGray3` not being available.

**Comment by kurabi** [comment]
> I don't know if this is due to Xcode 10 vs Xcode 11 weirdness, but even _with_ the `available(iOS 13.0, *)` statements, this now fails to compile in Xcode 10 because the compiler throws errors about those new colors `systemRed`, `systemGray5` and `systemGray3` not being available.

Unless something changed, Swift does not support conditional compilation. So the minimum Xcode version will be 11.0

If there is a way around this I am willing do it.

**Comment by ergunkocak** [comment]
Still does not compile in xcode 10.2.1 :(
using version 2.7.0

**Comment by kurabi** [comment]
Like I said, Xcode 11.0 is the new minimum. If you need to use Xcode 10.x, use the prior version as indicated in the README.md

**Pull request merged**
