### PR TITLE
Fix swipe cell's pan gesture recogniser interfering with scrolling when there aren't swipe actions for both sides of the cell

### PR DESCRIPTION
**Pull request by halleygen**
When there is a swipe action on only one side of the cell, the scrolling of the table/collection view can get "caught" if you don't move your finger vertically enough.

Below is a GIF of this bug.

img_8410

This PR changes some of the logic in the `gestureRecognizerShouldBegin:` delegate method to prevent this from happening.

### CODE REVIEW

**Comment by kurabi** [comment]
Is this still an issue? I see that you closed the PR.

**Comment by halleygen** [comment]
Yes, but I need to test the changes I made properly first. When I spent more time using SwipeCellKit with these changes in a real app I noticed that the problem wasnt entirely fixed.

**Comment by kurabi** [comment]
The issue though is that your swiping horizontally then switching to vertical. That’s considered one swipe gesture on iOS. So I am not sure this is an issue to begin with.

**Comment by halleygen** [comment]
I know that it is one gesture, but the problem is that the swipe cell pan gesture takes priority over the scroll view pan gesture, even when there are no swipe actions on one side of the cell. In this situation this makes it harder to scroll the scroll view, especially when you're holding your phone in one hand.

The GIF I posted wasn't very clear so hopefully these ones are better:

**Before my changes:**
notfixed
Notice that the scroll view gets stuck when your swipe isn't vertical enough, despite there being no leading swipe actions.

**After my changes:**
fixed
The swipe cell gesture does not begin so the scroll view can be scrolled normally.

**Comment by halleygen** [comment]
This actually works properly. The problems I thought there were were caused by another, unrelated gesture recogniser from the app I tested these changes in.

**Pull request closed without merging**
