### PR TITLE
Vertical centring (Fix issue #149)

### PR DESCRIPTION
**Pull request by halleygen**
This PR adds the ability to keep the title and image centred vertically at all times. As I mentioned in the issue (#149), this is useful when you have very tall table view cells that are not entirely visible for a lot of the time (eg. when viewing a chain of emails in Mail.app).

Below is a screenshot of the example app (with row height modified) before (left) and after (right) to illustrate these changes:
screen shot 2018-04-02 at 7 04 20 pm

To enable this feature you have to implement `func visibleTableViewRect() -> CGRect` in the cell's delegate. There is a default implementation in an extension of the delegate so existing users of SwipeCellKit would not experience a change in behaviour with their existing code. I did not use the weak reference to the table view that already exists in the `SwipeTableViewCell` class to get this rect because the new delegate function allows users to account for navigation bars/toolbars/etc that may be covering parts of the table view. 

I did not add a new property to control this behaviour to the `SwipeTableOptions`, since I think that it could be confusing for a user to have to enable it in the options as well as by implementing the delegate function, however, I can change this if you disagree.

The easiest way to see these changes in effect in the example app is by changing the table view's row height to 500 and implementing `visibleTableViewRect()` in the cell delegate. On iOS 11+, the simplest implementation would be: 
```swift
func visibleTableViewRect() -> CGRect {
     return tableView.safeAreaLayoutGuide.layoutFrame
}
```

Thanks,
halleygen

### CODE REVIEW

**Comment by kurabi** [comment]
Nice work @halleygen. Is there a reason you can think of as to why this can’t be on by default and then devs can implement the delegate for more custom use cases?

**Comment by halleygen** [comment]
It already kind of is on by default. I have made a minor change to try and make everything more clear.

The default implementation of `func visibleTableViewRect() -> CGRect?` returns `nil`, which results in a an offset of `0` being applied to the button image and title (i.e. it behaves the same way as the library does now). A non-zero offset is only calculated when the visible rect of the table view is provided by the delegate.

I didn't explain it very clearly in the OP, but the reason that you need the visible part is that often the table view is covered by bars (like in example app). If the vertical offset is calculated without taking these into account then the button title and image are not properly centred when only part of the cell is visible. In iOS 11+ this is not a problem because you can use the `safeAreaLayoutGuide.layoutFrame` property of the table view, however, on iOS 10 and below nothing like this exists (AFAIK), so you need to take the table view's bounds and adjust them to calculate the visible portion, accounting for navbars/toolbars/etc.

This means that there is no simple way (that I can think of) to make this just work for devs using SwipeCellKit and still support versions lower than iOS 11. Also, as there is the possibility of the table view being covered by a navigation bar or a tool bar or both or some other view, IMO almost every case would count as a custom use case.

At the moment, an implementation of `visibleTableViewRect()` in the example app for someone wanting to support versions lower than iOS 11 could be:
```swift 
extension MailViewController: SwipeTableViewCellDelegate {
    func visibleTableViewRect() -> CGRect? {
        if #available(iOS 11, *) {
            return tableView.safeAreaLayoutGuide.layoutFrame
        } else {
            // Can't use safe area so we have to get heights of navigation bar and tool bar, which obscure the top and bottom of the table view
            guard let navigationController = navigationController else { return .zero }
            
            let topAdjustment = navigationController.navigationBar.frame.height
            let bottomAdjustment = navigationController.toolbar?.frame.height ?? 0
            let bounds = tableView.bounds
            
            return CGRect(x: bounds.origin.x,
                          y: bounds.origin.y + topAdjustment,
                          width: bounds.width,
                          height: bounds.height - bottomAdjustment)
        }
    }
// ...
```

I hope that this clears things up (and that there is not some simple solution I have missed!)

**Comment by halleygen** [comment]
Maybe I could change it to to something like:
```swift 
public protocol SwipeTableViewCellDelegate: class {
    func tableViewVisibleRect(_ tableView: UITableView) -> CGRect?
// ...
}

public extension SwipeTableViewCellDelegate {
    func tableViewVisibleRect(_ tableView: UITableView) -> CGRect? {
        if #available(iOS 11, *) {
            return tableView.safeAreaLayoutGuide.layoutFrame
        } else {
            return nil
        }
    }
// ...
}
```

That way anyone targeting iOS 11+ gets it by default in most situations, without having to implement the delegate function themselves.

**Comment by kurabi** [comment]
We would need a sane default for iOS 9 and 10 though. I am just thinking to see if this is always on because most people have small cells, so things will just work. For those with big cells, default implementation will usually also just work, and the delegate is there to override for those with custom use cases.

**Comment by halleygen** [comment]
Ok, I understand. That makes sense. Is there anything else you want me to change?

**Comment by kurabi** [comment]
Off the top of my head, I think the delegate call back should be part of `SwipeTableViewCellDelegate`

We should add some documentation in the `Guides/Advanced.md` with a screenshot. I prefer you use a circular button style with no title (already supported by the library), similar to the Mail.app

**Comment by kurabi** [comment]
Yes, its already in there. my mistake. 

The `SwipeActionButtonDelegate` should be removed though.  You can add a the `verticalOffset(forSwipeActionButtonWithContentHeight contentHeight: CGFloat)` method to the `SwipeActionsViewDelegate` since the offset is for the whole `SwipeActionsView` which contains the swipe action buttons.

Then the `SwipeActionsView` can request the `verticalOffset(forSwipeActionButtonWithContentHeight contentHeight: CGFloat)` in the `addButtons` method via the delegate it has.

The `SwipeActionsViewDelegate` is implemented by ``SwipeTableViewCell` which then can call the `visibleTableViewRect`

**Comment by halleygen** [comment]
Ok, I've combined those two delegates and added some GIFs + instructions to the Advanced Guides document.

I also had to add a `verticalOffset` property to the `SwipeActionTransitioningContext` object because I discovered that the `ScaleTransition` no longer worked properly when the button content was offset.

**Comment by kurabi** [comment]
@halleygen Thanks! This is great.

> I also had to pass the vertical offset to the SwipeExpanding and SwipeTransitioning protocols because the custom transitions/expansions no longer worked properly when the button content was offset. This is fixed now.

Can you explain this a little more? What was not working correctly exactly?

**Comment by halleygen** [comment]
If the pic below you can see that the buttons move down as they grow. This happens because the vertical offset has not been taken into account during the transform so iOS treats the button content like it is still in the centre of the whole cell rather than the centre of the visible portion. 

<p align="center"></p>

To allow devs to take this into account in their custom expansions/transitions I added a `verticalOffset: CGFloat` property to the `SwipeActionTransitioningContext` struct, and changed `SwipeExpanding.actionButton(_ button: UIButton, didChange expanding: Bool, otherActionButtons: [UIButton])` to `SwipeExpanding.func actionButton(_ button: UIButton, didChange expanding: Bool, otherActionButtons: [UIButton], verticalOffset: CGFloat)`.

I wrote more about this at the end of the Advanced Guide markdown document if it's still not clear.

**Comment by kurabi** [comment]
@halleygen I see. Ya, UIKit is trying to be clever in animating the `UIButton`'s contents. I revised the solution to inset the `SwipeActionButtonWrapper` instead of the contents of the button. Please review and let me know if there is any issues.

**Comment by halleygen** [comment]
Using the insets seems like a much smarter way to do this. Everything works well with your changes, but for the edge case where the visible portion of the cell is shorter than the button content height is no longer handled. 

The screenshots below demonstrate this:

| Edge case accounted for  | Edge case unaccounted for |
|---|---|
| img_772b65de4c48-1 | img_a781d08c7416-1 |

Since you need the button's content size to do this I don't want to try to fix this without talking to you first.

**Comment by halleygen** [comment]
I made some changes that add an intrinsic content size + constraint priorities. Is this what you meant?

**Comment by kurabi** [comment]
Yep, that works. Now just need to make sure we didn't affect the main path, where this feature isn't being used.

**Comment by kurabi** [comment]
Thanks for your work on this @halleygen. Great feature.

**Comment by halleygen** [comment]
No problem. I've only been learning to program for a couple of months so it was nice to work with someone much more experienced!

**Pull request merged**
