### PR TITLE
Support for UICollectionView

### PR DESCRIPTION
**Pull request by gcox**
#4 

Initial support for UICollectionView.

Unfortunately, the fork [here](https://github.com/mschonvogel/SwipeCellKit) **replaced** support for UITableView with support for UICollectionView. This change **adds** support for UICollectionView.

Basically, this just copies all the `UITableView` related code/classes/etc and makes `UICollectionView` equivalents. `SwipeTableOptions.swift` was renamed to `SwipeOptions.swift` since it isn't table specific in any way (as far as I can tell). There's a lot of duplicated code between the two implementations, it may be worth it to refactor this to reduce that where it makes sense.

The example app was updated to add a `UICollectionView` example. The root VC is not a table view offering a choice between the TableView or CollectionView examples. The `UICollectionView` example was tweaked so it behaves more or less like a table view.

### CODE REVIEW

**Comment by kurabi** [comment]
Hi @gcox, This looks good! I am currently reviewing it over the next week and will see if any other changes would be needed to support `UICollectionView`

**Comment by ezar** [comment]
+1

**Comment by fishcharlie** [comment]
@kurabi Any updates on this?

**Comment by kidcosmic** [comment]
@kurabi please make this happen

**Comment by aleufms** [comment]
It will be nice.

**Comment by iamdew** [comment]
I like this!

**Comment by fishcharlie** [comment]
@kurabi There hasn't been any updates on this in a while. You still reviewing this?

**Comment by bernaferrari** [comment]
Up.. any update?

**Comment by GuiChevis** [comment]
@kurabi Any updates?

**Comment by kreeger** [comment]
Indeed, I'd like to ping on this @kurabi!

**Comment by kreeger** [comment]
I've been doing some testing on this branch and it's got some big problems when dealing with `UICollectionViewCell`s side-by-side in a flow layout. Take a look at this screenshot of the modified example project included with this PR:

simulator screen shot - ipad air 2 - 2018-01-22 at 13 13 35

- The cells don't remain masked to their own bounds
- Cells on the left-hand side of the window don't respond to touch; instead, the cells on the right handle the event and then jump over to the left as soon as they start panning
- Resetting the swipe only lines up the cell that _intercepted_ the pan with the cell that is to its left

I've been working on a copy of this branch to see if I can fix these bugs — I'll keep this thread posted with any updates, but @gcox or @mschonvogel if either of you are still around, some pointers would go a long way in helping!

**Comment by bernaferrari** [comment]
There is another problem, @kreeger, which is when you are using insets in your cell; the SwipeCellKit will ignore it and things will get ugly very fast. Hope you or someone else manage to fix it. I tried for a few days, but it was too much work.

**Comment by kreeger** [comment]
I've been making great progress on this today — I feel confident that tomorrow or Wednesday I'll be able to open a new pull request that includes @gcox's foundations and my updates. Stay tuned.

**Comment by kurabi** [comment]
@kreeger looking forward to seeing it.

**Comment by kreeger** [comment]
@kurabi @gcox The updated pull request has been posted (#142)! This one can be closed in favor of the other one.

**Pull request closed without merging**
